# Generated by Django 3.2.6 on 2021-08-26 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 26, 14, 41, 52, 321892)),
        ),
    ]
