# Generated by Django 3.2.6 on 2021-08-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merch'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='merch',
            field=models.ManyToManyField(to='main_app.Merch'),
        ),
    ]
